name: pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            go-version: 1.21.0
            args: build
          - os: ubuntu-latest
            go-version: 1.21.0
            args: lint
          - os: ubuntu-latest
            go-version: 1.21.0
            args: test
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: /home/runner/go

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Golang Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run ${{ matrix.args }}
        run: make ${{ matrix.args }}
